### ISSUE TITLE
include class to override the visual order of grid items

### ISSUE THREAD

**Issue by DrizzlyOwl** [lukewhitehouse/groot#8]
whilst leaving html order alone.

``` scss
/**
 * Custom fancy float
 */

.#{$gr-item-unit}--omega {
    float: right;
}
```

Usage:

``` html
<div class="grid">
    <div class="grid__item grid__item--omega" id="first"></div>
    <div class="grid__item" id="last"></div>
</div>
```

Results in `#first` appearing at the right of the grid instead of at the beginning.

This could be extended upon by inclusion of the breakpoints.
